export const initialState = [
  {
    Name: 'Charlie',
    Gender: 'Male',
    Breed: 'Dog',
    Weight: 12,
    Age: 3,
  },
  {
    Name: 'Max',
    Gender: 'Male',
    Breed: 'Dog',
    Weight: 23,
    Age: 7,
  },
  {
    Name: 'Lucy',
    Gender: 'Female',
    Breed: 'Cat',
    Weight: 5,
    Age: 4,
  },
  {
    Name: 'Oscar',
    Gender: 'Male',
    Breed: 'Turtle',
    Weight: 13,
    Age: 23,
  },
  {
    Name: 'Daisy',
    Gender: 'Female',
    Breed: 'Bird',
    Weight: 1.7,
    Age: 3,
  },
  {
    Name: 'Ruby',
    Gender: 'Female',
    Breed: 'Dog',
    Weight: 6,
    Age: 3,
  },
  {
    Name: 'Milo',
    Gender: 'Male',
    Breed: 'Dog',
    Weight: 11,
    Age: 7,
  },
  {
    Name: 'Toby',
    Gender: 'Male',
    Breed: 'Dog',
    Weight: 34,
    Age: 19,
  },
  {
    Name: 'Lola',
    Gender: 'Female',
    Breed: 'Cat',
    Weight: 4,
    Age: 3,
  },
  {
    Name: 'Jack',
    Gender: 'Male',
    Breed: 'Turtle',
    Weight: 13,
    Age: 23,
  },
  {
    Name: 'Bailey',
    Gender: 'Female',
    Breed: 'Bird',
    Weight: 2,
    Age: 4,
  },
  {
    Name: 'Bella',
    Gender: 'Female',
    Breed: 'Dog',
    Weight: 6,
    Age: 10,
  },
  {
    Name: 'Charliy',
    Gender: 'Male',
    Breed: 'Dog',
    Weight: 10,
    Age: 2,
  },
  {
    Name: 'Belisima',
    Gender: 'Female',
    Breed: 'Dog',
    Weight: 3,
    Age: 17,
  },
]

export const columnsInitialState = ['Name', 'Gender', 'Breed', 'Weight', 'Age']
